#!/bin/ksh
#
# $OpenBSD: v2ray,v 1.4 2018/01/11 19:52:12 rpe Exp $

daemon="/usr/local/bin/v2ray"
daemon_flags="-confdir /etc/v2ray/"
daemon_user=www

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1
